title: Your awesome title
author: GitHub User
email: tinadancau12@gmail.com
description: > # this means to ignore newlines until "baseurl:"
 Tina Dancau
linkedin_username: tinadancau
github_username:  tdancau

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
header_pages:
 - about.html

# Build settings
# markdown: kramdown
theme: jekyll-theme-cayman

